In [10]:
import pandas as pd
import duckdb

In [19]:
con = duckdb.connect('games.duckdb');

In [15]:
franchise_data = con.execute('SELECT name, franchise_duration, franchise_genre FROM franchises').df()

In [16]:
franchise_data.sort_values('franchise_duration', ascending=False, inplace=True)

In [17]:
franchise_data

               name  franchise_duration             franchise_genre
2449           FIFA               51.20                       Sport
2445         Marvel               48.00  Hack and slash/Beat 'em up
2329            NFL               46.68                       Sport
2389      Star Trek               46.17                     Shooter
2284            NHL               45.70                       Sport
...             ...                 ...                         ...
2484       gayporno                 NaN                        None
2488        Asteria                 NaN                        None
2489  Wheel of Time                 NaN                        None
2490       Sukisyo!                 NaN                        None
2491       Sukisho!                 NaN                        None

[2492 rows x 3 columns]

In [21]:
games = con.execute('SELECT name, steamid FROM games').df()

In [24]:
games.sort_values('steamId', ascending=False, inplace=True)

In [25]:
games

                                     name  steamId
63870                Tammuz: Blood & Sand  4164840
308944      Japanese Rural Life Adventure  4158870
83371                      Perished Truth  4152560
127236                       Grapple Bear  4151550
132291                 Dare Up Adrenaline  4141620
...                                   ...      ...
332574                      Patrician 1+2     <NA>
332575  Empires: Dawn of the Modern World     <NA>
332585                    Prehistorik 1+2     <NA>
332593   Speed Busters: American Highways     <NA>
332596                     Catacombs Pack     <NA>

[332600 rows x 2 columns]

In [46]:
demo = games[games['steamId'] == 730]

In [47]:
demo

                                    name  steamId
109722  Counter-Strike: Global Offensive      730

In [45]:
import requests
steam_api = "https://store.steampowered.com/api/appdetails?appids=730"
response = requests.get(steam_api)
data = response.json()

print('Game Name: ', data['730']['data']['name'])
print('Steam ID: ', data['730']['data']['steam_appid'])

Game Name:  Counter-Strike 2
Steam ID:  730

In [31]:
con.close()